---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 11:44
---

--package.path = './lib/thinkutils/common/?.lua;' .. package.path
--package.path = package.path .. ';./common/?.lua';

local thinkutils = {}
thinkutils.common = {}

local datetime = require "thinkutils/common/datetime"
thinkutils.common.datetime = datetime

local stringutils = require "thinkutils/common/stringutils"
thinkutils.common.string = stringutils

--local json = require("common.json")
--thinkutils.common.json = json

--local csvutils = require("common.csvutils")
--thinkutils.common.csvutils = csvutils

thinkutils.common.max = function (a, b)
    if a >= b then
        return a
    else
        return b
    end
end

thinkutils.common.min = function (a, b)
    if a <= b then
        return a
    else
        return b
    end
end

return thinkutils
