---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangxiaofeng.
--- DateTime: 2020/12/10 13:27
---

local stringutils = {}

stringutils.split = function (s, p)
    local rt= {}
    string.gsub(s, '[^'..p..']+', function(w) table.insert(rt, w) end )

    return rt
end

stringutils.trim = function (szTxt)
    return (szTxt:gsub("^%s*(.-)%s*$", "%1"))
end

stringutils.is_empty = function (szTxt)
    return nil == szTxt or #(stringutils.trim(szTxt)) <= 0
end

stringutils.is_email = function (szTxt)
    if string.len(szTxt or "") < 6 then return false end
    local b,e = string.find(szTxt or "", '@')
    local bstr = ""
    local estr = ""
    if b then
        bstr = string.sub(szTxt, 1, b-1)
        estr = string.sub(szTxt, e+1, -1)
    else
        return false
    end

    -- check the string before '@'
    local p1,p2 = string.find(bstr, "[%w_]+")
    if (p1 ~= 1) or (p2 ~= string.len(bstr)) then return false end

    -- check the string after '@'
    if string.find(estr, "^[%.]+") then return false end
    if string.find(estr, "%.[%.]+") then return false end
    if string.find(estr, "@") then return false end
    if string.find(estr, "%s") then return false end --空白符
    if string.find(estr, "[%.]+$") then return false end

    local _,count = string.gsub(estr, "%.", "")
    if (count < 1 ) or (count > 3) then
        return false
    end

    return true
end

stringutils.is_number = function (szTxt)
    return string.match(szTxt, "%d+") == szTxt
end

stringutils.is_phone = function (szTxt)
    return string.match(szTxt,"[1][3-9]%d%d%d%d%d%d%d%d%d") == szTxt
end

stringutils.to_char_list = function (szTxt)
    local lstRet = {}
    for i = 1, #szTxt do
        table.insert(lstRet, string.char(string.byte(szTxt, i, i)))
    end

    return lstRet
end

stringutils.to_asc_list = function (szTxt)
    local lstRet = {}
    for i = 1, #szTxt do
        table.insert(lstRet, string.byte(szTxt, i, i))
    end

    return lstRet
end

return stringutils